changelog:
  categories:
    - title: Bugfixes
      labels:
        - bug
    - title: New Features and Changes
      labels:
        - enhancement
    - title: Updates
      labels:
        - chore
