changelog:
  categories:
    - title: Bugfixes
      labels:
        - bug
    - title: New Features and Changes
      labels:
        - enhancement
    - title: Technical Details
      labels:
        - chore
  change-template: '- $TITLE'
