name: Add Labels From Issue to PR

on:
  pull_request:
    types: [opened]


jobs:
  retrieve-issue-labels:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: read
      deployments: read
      id-token: write
      issues: read 
      packages: write      
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Get Issue Key From Branch
        id: get-issue-key
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.event.pull_request.head.ref }}

      - name: Get Issue Properties
        id: issue
        uses: frieder/jira-issue-info@v1
        with:
          issue: ${{ steps.get-issue-key.outputs.issue }}

      - name: Get Set Inputs
        run: |
          echo "ISSUE_TYPE=${{fromJSON(steps.issue.outputs.json).fields.issuetype.name}}" >> "$GITHUB_ENV"          


      - name: Download jira-issue-types.json with curl
        run: |
          curl -o slack-channels.json https://sn01genstorage.blob.core.windows.net/app-resources/jira-issue-types.json
          echo label=$(jq -r '."${{ env.ISSUE_TYPE }}"' ./jira-issue-types.json) >> $GITHUB_ENV
      
      - name: Testing Output
        run: echo "${{ env.label }}"
    
      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "${{ env.label }}"
          number: ${{ github.event.pull_request.number }}
