name: Add Labels From Issue to PR

on:
  pull_request:
    types: [opened, reopened]

env:
  NEEDS_LABEL: true

jobs:
  retrieve-issue-labels:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: read
      deployments: read
      id-token: write
      issues: read 
      packages: write      
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Get Issue Key From Branch
        id: get-issue-key
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.event.pull_request.head.ref }}

      - name: Get Issue Properties
        id: issue
        uses: frieder/jira-issue-info@v1
        with:
          issue: ${{ steps.get-issue-key.outputs.issue }}

      - name: Get Set Inputs
        run: |
          echo "ISSUE_TYPE=${{fromJSON(steps.issue.outputs.json).fields.issuetype.name}}" >> "$GITHUB_ENV"          

      - name: Download jira-issue-types.json with curl
        run: |
          curl -o jira-issue-types.json https://sn01genstorage.blob.core.windows.net/app-resources/jira-issue-types.json

      - name: If Issue Is a Subtask Get Parent Issue
        if: ${{ fromJSON(steps.issue.outputs.json).fields.issuetype.name == 'Sub-task' }}
        id: parent_issue
        uses: frieder/jira-issue-info@v1
        with:
          issue: ${{ fromJSON(steps.issue.outputs.json).fields.parent.key }}

      - name: If Issue Is a Subtask and All Other Subtasks Are Done, Set "Issue Type" to Parent For Correct Label
        if: |
          fromJSON(steps.issue.outputs.json).fields.issuetype.name == 'Sub-task' &&
          !contains(fromJSON(steps.parent_issue.outputs.json).fields.subtasks.*.fields.status.name, 'To Do') &&
          !contains(fromJSON(steps.parent_issue.outputs.json).fields.subtasks.*.fields.status.name, 'In Progress') &&
          !contains(fromJSON(steps.parent_issue.outputs.json).fields.subtasks.*.fields.status.name, 'In Code Review')
        run: echo "ISSUE_TYPE=${{fromJSON(steps.parent_issue.outputs.json).fields.issuetype.name}}" >> "$GITHUB_ENV"

      - name: Derive Label
        if: ${{ env.ISSUE_TYPE != 'Subtask' }}
        run: |
          echo label=$(jq -r '."${{ env.ISSUE_TYPE }}"' ./jira-issue-types.json) >> $GITHUB_ENV     
          
      - name: Add labels
        if: ${{ env.ISSUE_TYPE != 'Subtask' }}      
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "${{ env.label }}"
          number: ${{ github.event.pull_request.number }}
