name: jira hook

on:
   workflow_dispatch:

jobs:
  get-jira-properties:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: read
      deployments: read
      id-token: write
      issues: read 
      packages: write      
      pull-requests: write    

    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Get Issue Properties
      id: issue
      uses: frieder/jira-issue-info@v1
      with:
        issue: FLEX-9

    - name: Get Issue Type
      id: determine-issue-type
      run: echo "issue_type=${{fromJSON(steps.issue.outputs.json).fields.issuetype.name}}" >> "$GITHUB_OUTPUT" 

    - name: Get Parent Issue
      if: ${{ (steps.determine-issue-type.outputs.issue_type == 'Subtask') }}
      id: parent_issue
      uses: frieder/jira-issue-info@v1
      with:
        issue: ${{fromJSON(steps.issue.outputs.json).fields.parent.key}}

    - name: Determine If All Subtasks Are Done
      id: parent_check
      run: |
          if echo "${{steps.parent_issue.outputs.json}}" | jq -e '(.fields.subtasks | map(.fields.status.name == "Done") | all)'; then
            echo "all_done=true" >> $GITHUB_OUTPUT
          else
            echo "all_done=false" >> $GITHUB_OUTPUT
          fi

    - name: All Subtasks Done
      if: ${{ (steps.parent_check.outputs.all_done == 'true') }}
      run: echo "All subtasks are done"

    - name: All Subtasks Not Done
      if: ${{ (steps.parent_check.outputs.all_done == 'false') }}
      run: echo "All subtasks are not done"
