name: PRCreate-Jira-Properties
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  get-jira-properties:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: read
      deployments: read
      id-token: write
      issues: read 
      packages: write      
      pull-requests: write    
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Get Issue Key From Branch
      id: get-issue-key
      uses: atlassian/gajira-find-issue-key@v3
      with:
        string: ${{ github.head_ref }}

    - name: Get Issue Properties
      id: issue
      uses: frieder/jira-issue-info@v1
      with:
        issue: ${{ steps.get-issue-key.outputs.issue }} 

    - name: Get Issue Type
      id: determine-issue-type
      run: echo "issue_type=${{fromJSON(steps.issue.outputs.json).fields.issuetype.name}}" >> "$GITHUB_OUTPUT"

    - name: Set Bug Label
      if: ${{ steps.determine-issue-type.outputs.issue_type == 'Bug' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: "bug"
        number: ${{ github.event.pull_request.number }}


    - name: Set Task Label
      if: ${{ steps.determine-issue-type.outputs.issue_type == 'Task' }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: "chore"
        number: ${{ github.event.pull_request.number }}


    - name: Set Story Label
      if: ${{ (steps.determine-issue-type.outputs.issue_type == 'Story') }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: "enhancement"
        number: ${{ github.event.pull_request.number }}
          
      
      
