name: Flag Tag as Release
on:
  release:
    types:
      - created  
jobs:
  flag-tag:   
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v3
      - name: Update Tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.release.tag_name }}-r',
              sha: context.sha
            })            
