name: Increment semantic version
on:
  pull_request:
    types:
      - closed  
jobs:
  increment-version:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Get Issue Key From Branch
        id: get-issue-key
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: FLEX-2
          # string: ${{ github.event.pull_request.head.ref }}

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.get-issue-key.outputs.issue }}
          transition: "Done"

      - name: Get Issue Properties
        id: issue
        uses: frieder/jira-issue-info@v1
        with:
          issue: ${{ steps.get-issue-key.outputs.issue }}
        
      - name: Get Set Inputs
        run: |
          echo "CURRENT_VERSION=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
          echo "ISSUE_TYPE=${{fromJSON(steps.issue.outputs.json).fields.issuetype.name}}" >> "$GITHUB_ENV"

      - name: If Subtask Get Parent Issue
        if: ${{ fromJSON(steps.issue.outputs.json).fields.issuetype.name == 'Subtask' }}
        id: parent_issue
        uses: frieder/jira-issue-info@v1
        with:
          issue: ${{ fromJSON(steps.issue.outputs.json).fields.parent.key }}

      - name: If All Other Subtasks Are Done
        if: |
          fromJSON(steps.issue.outputs.json).fields.issuetype.name == 'Subtask' &&
          !contains(fromJSON(steps.parent_issue.outputs.json).fields.subtasks.*.fields.status.name, 'To Do') &&
          !contains(fromJSON(steps.parent_issue.outputs.json).fields.subtasks.*.fields.status.name, 'In Progress') &&
          !contains(fromJSON(steps.parent_issue.outputs.json).fields.subtasks.*.fields.status.name, 'In Code Review')
        run: echo "ISSUE_TYPE=Story" >> "$GITHUB_ENV"
        
      
      - name: Increment Version
        id: increment-version
        uses: JesseBroxterman/semantic-version-increment@v2.0.6
        with:
          current_version: ${{ env.CURRENT_VERSION }}
          issue_type: ${{ env.ISSUE_TYPE }}
                 
      - name: Add New Tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.increment-version.outputs.new_version }}',
              sha: context.sha
            })  

      - name: Set repository variable using REST API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/DEV_VERSION \
            -d '{"name":"DEV_VERSION","value":"${{ steps.increment-version.outputs.new_version }}"}'
