name: Slack - Review Request
on:
  pull_request:
    types: [ review_requested ]
      
jobs:
  SendSlackReviewRequest:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
         echo "$GITHUB_CONTEXT"
         echo ${{ github.event.pull_request.requested_reviewers[-1].id }}
