name: Slack - Review Request
on:
  pull_request:
    types: [ review_requested ]
      
jobs:
  SendSlackReviewRequest:
    runs-on: ubuntu-latest
    steps:
     - name: Get UserID
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
         echo "$GITHUB_CONTEXT"
         echo "userID=${{ github.event.requested_reviewer.id }}" >> $GITHUB_ENV

     - name: Check ID
       run: |
         echo "${{ env.userID }}"

     - uses: actions/checkout@v3
         
     - name: Parse JSON for Channel ID
       run: |
         channel=$(jq -r '."${{ env.userID }}"' ./slack-channels.json)
         echo "channelID=$channel"  >> $GITHUB_ENV

         
     - name: Check Channel ID
       run: |
         echo "${{ env.channelID }}"
         
     - name: Post to a Slack channel
       id: slack
       uses: slackapi/slack-github-action@v1.25.0
       with:
         # Slack channel id, channel name, or user id to post message.
         # See also: https://api.slack.com/methods/chat.postMessage#channels
         # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
         channel-id: '${{ env.channelID }}'
         # For posting a simple plain text message
         slack-message: "Test"
       env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_REVIEW_REQUEST_TOKEN }}
