name: Slack - Review Request
on:
  pull_request:
    types: [ review_requested ]
      
jobs:
  SendSlackReviewRequest:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       id: first
       env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
         echo "$GITHUB_CONTEXT"
         echo "userID=${{ github.event.pull_request.requested_reviewers[0].id }}" >> $GITHUB_ENV

     - name: Check ID
       run: |
         echo "${{ env.userID }}"

     - uses: actions/checkout@v3

     - name: Download and parse JSON file
       run: |
         value=$(jq -r '.${{ env.userID }}' ./slack-channels.json)
         echo "channelID=$value" >> $GITHUB_ENV

     - name: Post to a Slack channel
       id: slack
       uses: slackapi/slack-github-action@v1.25.0
       with:
         # Slack channel id, channel name, or user id to post message.
         # See also: https://api.slack.com/methods/chat.postMessage#channels
         # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
         channel-id: '${{ env.channelID }}'
         # For posting a simple plain text message
         slack-message: "Test"
       env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_REVIEW_REQUEST_TOKEN }}
