name: trivy check
on:
  workflow_dispatch:

jobs:
  build:
    name: Checkout and Scan
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: false
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

